FROM alpine:latest

# https://mirrors.alpinelinux.org/
RUN sed -i 's@dl-cdn.alpinelinux.org@ftp.halifax.rwth-aachen.de@g' /etc/apk/repositories

RUN apk update
RUN apk upgrade

# required althttpd
RUN apk add --no-cache \
  gcc make linux-headers musl-dev \
  openssl-libs-static openssl-dev \
  sqlite-static sqlite-dev ripgrep curl bash

ENV XZ_OPT=-e9
COPY build-static-althttpd-alpine.sh  build-static-althttpd-alpine.sh
RUN chmod +x ./ build-static-althttpd-alpine.sh
RUN bash ./ build-static-althttpd-alpine.sh
